import { SectionIntro } from "@/components/marketing/Section";

/**
 * Market-intelligence matrix — the data-table surface of the public site.
 * Dense, edge-to-edge, tabular numerals with aligned decimals. Amber is
 * used only where a structural signal is active; everything else stays
 * monochrome. Values are representative, generated by the same engines
 * that drive the terminal.
 */

type Row = {
  sym: string;
  name: string;
  last: string;
  d1: string;
  d1p: string;
  vol20: string;
  var95: string;
  z: string;
  signal: string;
  active: boolean;
  regime: string;
};

const ROWS: Row[] = [
  { sym: "SPX", name: "S&P 500", last: "5,973.10", d1: "+21.42", d1p: "+0.36", vol20: "11.2", var95: "−1.84", z: "+0.42", signal: "Neutral", active: false, regime: "Carry" },
  { sym: "NDX", name: "Nasdaq 100", last: "21,764.83", d1: "+109.11", d1p: "+0.50", vol20: "15.8", var95: "−2.61", z: "+0.87", signal: "Momentum", active: true, regime: "Carry" },
  { sym: "RTY", name: "Russell 2000", last: "2,241.35", d1: "−8.72", d1p: "−0.39", vol20: "18.4", var95: "−3.05", z: "−1.12", signal: "Neutral", active: false, regime: "Compression" },
  { sym: "US10Y", name: "US 10-year yield", last: "4.212", d1: "−0.021", d1p: "−0.49", vol20: "6.1", var95: "−0.72", z: "−0.35", signal: "Mean-revert", active: true, regime: "Rebalance flow" },
  { sym: "DXY", name: "Dollar index", last: "103.418", d1: "−0.124", d1p: "−0.12", vol20: "5.4", var95: "−0.66", z: "−0.18", signal: "Neutral", active: false, regime: "Compression" },
  { sym: "EURUSD", name: "Euro / dollar", last: "1.0862", d1: "+0.0019", d1p: "+0.18", vol20: "5.9", var95: "−0.71", z: "+0.24", signal: "Neutral", active: false, regime: "Carry" },
  { sym: "WTI", name: "Crude oil · WTI", last: "78.42", d1: "+0.84", d1p: "+1.08", vol20: "24.6", var95: "−3.92", z: "+1.64", signal: "Breakout watch", active: true, regime: "Liquidity vacuum" },
  { sym: "XAU", name: "Gold spot", last: "2,648.20", d1: "+4.10", d1p: "+0.16", vol20: "12.3", var95: "−1.97", z: "+0.09", signal: "Neutral", active: false, regime: "Carry" },
  { sym: "VIX", name: "Volatility index", last: "14.86", d1: "−0.42", d1p: "−2.75", vol20: "—", var95: "—", z: "−0.94", signal: "Gamma pin", active: true, regime: "Dealer hedging" },
  { sym: "BTC", name: "Bitcoin / USD", last: "97,412.55", d1: "+1,204.18", d1p: "+1.25", vol20: "41.7", var95: "−6.58", z: "+0.71", signal: "Momentum", active: true, regime: "Risk transfer" },
];

const HEADERS: { label: string; align: "left" | "right" }[] = [
  { label: "Sym", align: "left" },
  { label: "Instrument", align: "left" },
  { label: "Last", align: "right" },
  { label: "Δ 1D", align: "right" },
  { label: "Δ 1D%", align: "right" },
  { label: "σ 20D%", align: "right" },
  { label: "VaR95%", align: "right" },
  { label: "Z", align: "right" },
  { label: "Signal", align: "left" },
  { label: "Regime", align: "left" },
];

export default function MarketMatrix() {
  return (
    <section className="bg-carbon-950 border-b border-hairline">
      <div className="max-w-7xl mx-auto px-5 sm:px-8 py-20 sm:py-28">
        <SectionIntro
          index="03"
          label="Market intelligence"
          title={
            <>
              The whole surface,
              <br />
              <span className="text-white/40">one screen deep.</span>
            </>
          }
          lede="Every instrument carries its distribution with it: realized volatility, tail risk, mean-reversion state and the structural regime the CLANK engine has it filed under. This is the resolution the terminal operates at."
        />

        <div className="mt-14 border border-hairline bg-carbon-900 overflow-x-auto">
          {/* Table chrome */}
          <div className="flex items-center justify-between px-4 h-9 border-b border-hairline min-w-[960px]">
            <span className="mkt-label text-[10px] text-white/45">Cross-asset monitor</span>
            <span className="flex items-center gap-4">
              <span className="mkt-num text-[10px] text-white/30">10 INSTRUMENTS · 4 ASSET CLASSES</span>
              <span className="flex items-center gap-1.5">
                <span className="h-1.5 w-1.5 bg-signal" aria-hidden="true" />
                <span className="mkt-label text-[10px] text-signal">Live</span>
              </span>
            </span>
          </div>

          <table className="w-full min-w-[960px]">
            <thead>
              <tr className="border-b border-hairline">
                {HEADERS.map((h) => (
                  <th
                    key={h.label}
                    className={`mkt-label text-[9px] text-white/30 font-medium px-4 py-2.5 ${h.align === "left" ? "text-left" : "text-right"}`}
                  >
                    {h.label}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {ROWS.map((r) => {
                const down = r.d1.startsWith("−");
                return (
                  <tr
                    key={r.sym}
                    className="border-b border-hairline-faint last:border-b-0 hover:bg-carbon-750 transition-colors duration-150 ease-out"
                  >
                    <td className="px-4 py-2 mkt-num text-[12px] text-white/90">{r.sym}</td>
                    <td className="px-4 py-2 text-[12px] tracking-tight text-white/50">{r.name}</td>
                    <td className="px-4 py-2 mkt-num text-[12px] text-white/85 text-right">{r.last}</td>
                    <td className={`px-4 py-2 mkt-num text-[12px] text-right ${down ? "text-neg" : "text-pos"}`}>{r.d1}</td>
                    <td className={`px-4 py-2 mkt-num text-[12px] text-right ${down ? "text-neg" : "text-pos"}`}>{r.d1p}</td>
                    <td className="px-4 py-2 mkt-num text-[12px] text-white/55 text-right">{r.vol20}</td>
                    <td className="px-4 py-2 mkt-num text-[12px] text-white/70 text-right">{r.var95}</td>
                    <td className="px-4 py-2 mkt-num text-[12px] text-white/55 text-right">{r.z}</td>
                    <td className={`px-4 py-2 mkt-label text-[9px] ${r.active ? "text-signal" : "text-white/35"}`}>{r.signal}</td>
                    <td className="px-4 py-2 mkt-label text-[9px] text-white/45">{r.regime}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>

          <div className="flex items-center justify-between px-4 h-8 border-t border-hairline min-w-[960px]">
            <span className="mkt-num text-[9px] text-white/30">σ FROM 20D LOG-RETURNS · VaR HISTORICAL, 252D WINDOW · Z VS OU MEAN</span>
            <span className="mkt-num text-[9px] text-white/30 hidden lg:inline">REPRESENTATIVE VALUES</span>
          </div>
        </div>
      </div>
    </section>
  );
}
