const KNOWN_INDIAN_BASE = new Set([
  "WIPRO", "TCS", "INFY", "RELIANCE", "HDFCBANK", "ICICIBANK", "SBIN", "TATAMOTORS", "BHARTIARTL", "ITC",
  "KOTAKBANK", "LT", "AXISBANK", "MARUTI", "SUNPHARMA", "TITAN", "BAJFINANCE", "HCLTECH", "ADANIENT", "ADANIPORTS",
  "TECHM", "HINDUNILVR", "POWERGRID", "NTPC", "ONGC", "COALINDIA", "BPCL", "JSWSTEEL", "TATASTEEL", "DRREDDY",
  "CIPLA", "DIVISLAB", "ULTRACEMCO", "GRASIM", "NESTLEIND", "BAJAJFINSV", "HEROMOTOCO", "EICHERMOT", "APOLLOHOSP",
  "HINDALCO", "VEDL", "MRF", "IRCTC", "ETERNAL", "ZOMATO", "PAYTM", "NYKAA", "DMART", "TRENT", "JIOFIN",
  "IOC", "TATAPOWER", "TATACHEM", "INDUSINDBK", "BANKBARODA", "PNB", "CANBK", "FEDERALBNK",
  "MOTHERSON", "HAVELLS", "VOLTAS", "GODREJCP", "DABUR", "BRITANNIA", "PIDILITIND", "ASIANPAINT",
  "SBILIFE", "HDFCLIFE", "ICICIPRULI", "ICICIGI", "SBICARD", "CHOLAFIN",
  "HAL", "BEL", "BHEL", "RECLTD", "PFC", "IRFC", "SAIL", "NHPC", "SJVN",
  "INDIGO", "TATAELXSI", "PERSISTENT", "LTIM", "MPHASIS", "COFORGE",
]);

const INDIAN_ALIASES: Record<string, string> = {
  SBI: "SBIN", STATEBANKOFINDIA: "SBIN", STATEBANKIND: "SBIN", STATEBANK: "SBIN",
  TATA: "TATAMOTORS", TATASTEEL: "TATASTEEL", TATASTEELLTD: "TATASTEEL", TATASTEELLIMITED: "TATASTEEL",
  TATAPOWER: "TATAPOWER", TATACHEM: "TATACHEM",
  RELIANCE: "RELIANCE", RIL: "RELIANCE", RELIANCEINDUSTRIES: "RELIANCE",
  HDFC: "HDFCBANK", HDFCBANKLIMITED: "HDFCBANK",
  ICICI: "ICICIBANK", ICICIBANKLIMITED: "ICICIBANK",
  KOTAK: "KOTAKBANK", KOTAKMAHINDRA: "KOTAKBANK", KOTAKMAHINDRABANK: "KOTAKBANK",
  AXIS: "AXISBANK", AXISBANKLIMITED: "AXISBANK",
  BHARTI: "BHARTIARTL", AIRTEL: "BHARTIARTL", BHARTIAIRTEL: "BHARTIARTL",
  BAJAJ: "BAJFINANCE", BAJAJFINANCE: "BAJFINANCE", BAJAJFINSERV: "BAJAJFINSV",
  HINDALCOINDUSTRIES: "HINDALCO", HINDALCO: "HINDALCO",
  HEROHONDA: "HEROMOTOCO", HERO: "HEROMOTOCO", HEROMOTOCORP: "HEROMOTOCO",
  ZOMATO: "ETERNAL", ETERNAL: "ETERNAL",
  NYKAA: "NYKAA", FABORENYKAA: "NYKAA",
  PAYTM: "PAYTM", ONE97: "PAYTM",
  INFOSYS: "INFY", INFOSYSLIMITED: "INFY", INFOSYSLTD: "INFY",
  WIPROLIMITED: "WIPRO", WIPRO: "WIPRO",
  HCLTECH: "HCLTECH", HCL: "HCLTECH", HCLTECHNOLOGIES: "HCLTECH",
  SUNPHARMA: "SUNPHARMA", SUNPHARMAADVANCEDRESEARCH: "SUNPHARMA",
  DRREDDY: "DRREDDY", DRREDDYS: "DRREDDY", DRREDDI: "DRREDDY", DRREDDYSLABORATORIES: "DRREDDY",
  MARUTISUZUKI: "MARUTI", MARUTI: "MARUTI",
  EICHERMOTORS: "EICHERMOT", EICHER: "EICHERMOT",
  APOLLO: "APOLLOHOSP", APOLLOHOSPITALS: "APOLLOHOSP", APOLLOHOSPITAL: "APOLLOHOSP",
  ULTRACEMENTO: "ULTRACEMCO", ULTRATECH: "ULTRACEMCO", ULTRATECHCEMENT: "ULTRACEMCO",
  POWERGRID: "POWERGRID", PGCIL: "POWERGRID", POWERGRIDCORPORATION: "POWERGRID",
  COALINDIA: "COALINDIA", CIL: "COALINDIA",
  ONGC: "ONGC", OILANDNATURALGAS: "ONGC",
  NTPC: "NTPC", NTPCLIMITED: "NTPC",
  BPCL: "BPCL", BHARATPETROLEUM: "BPCL",
  IOC: "IOC", INDIANOIL: "IOC", INDIANOILCORPORATION: "IOC",
  JSWSTEEL: "JSWSTEEL", JSW: "JSWSTEEL",
  DMART: "DMART", AVENUESUPER: "DMART", AVENUESSUPERMARTS: "DMART",
  TRENT: "TRENT", TRENTLIMITED: "TRENT",
  TITAN: "TITAN", TITANCOMPANY: "TITAN",
  JIOFIN: "JIOFIN", JIOFINANCIAL: "JIOFIN", JIOFINANCIALSERVICES: "JIOFIN",
  ITC: "ITC", ITCLIMITED: "ITC",
  LT: "LT", LARSEN: "LT", LARSENANDTOUBRO: "LT", LARSENTOUBRO: "LT",
  VEDANTA: "VEDL", VEDL: "VEDL", VEDANTALIMITED: "VEDL",
  MRF: "MRF", MRFLIMITED: "MRF",
  IRCTC: "IRCTC",
  HAL: "HAL", HINDUSTANAERONAUTICS: "HAL",
  BEL: "BEL", BHARATELECTRONICS: "BEL",
  BHEL: "BHEL", BHARATHEAVYELECTRICALS: "BHEL",
  INDIGO: "INDIGO", INTERGLOBE: "INDIGO", INTERGLOBEAVIATION: "INDIGO",
  TATAELXSI: "TATAELXSI",
  ASIANPAINT: "ASIANPAINT", ASIANPAINTS: "ASIANPAINT",
  DABUR: "DABUR", DABURINDIA: "DABUR",
  BRITANNIA: "BRITANNIA",
  GODREJCP: "GODREJCP", GODREJ: "GODREJCP", GODREJCONSUMERPRODUCTS: "GODREJCP",
  MOTHERSON: "MOTHERSON", MOTHERSONSUMI: "MOTHERSON",
  HAVELLS: "HAVELLS", HAVELLSINDIA: "HAVELLS",
  VOLTAS: "VOLTAS",
  NESTLEINDIA: "NESTLEIND", NESTLE: "NESTLEIND", NESTLEIND: "NESTLEIND",
  PNB: "PNB", PUNJABNATONALBANK: "PNB", PUNJABNATIONALBANK: "PNB",
  BANKOFBARODA: "BANKBARODA", BANKBARODA: "BANKBARODA",
  CANARABANK: "CANBK", CANBK: "CANBK",
  FEDERALBANK: "FEDERALBNK", FEDERALBNK: "FEDERALBNK",
  INDUSINDBK: "INDUSINDBK", INDUSINDBANK: "INDUSINDBK", INDUSIND: "INDUSINDBK",
  SAIL: "SAIL", STEELAUTHORITY: "SAIL",
  NHPC: "NHPC", RECLTD: "RECLTD", REC: "RECLTD",
  PFC: "PFC", POWERFIN: "PFC", POWERFINANCECORPORATION: "PFC",
  IRFC: "IRFC",
  SJVN: "SJVN",
  CHOLAFIN: "CHOLAFIN", CHOLAMANDALAM: "CHOLAFIN",
  SBILIFE: "SBILIFE", SBILIFEINSUARANCE: "SBILIFE",
  HDFCLIFE: "HDFCLIFE", HDFCLIFEINSUARANCE: "HDFCLIFE",
  GRASIM: "GRASIM", GRASIMINDUSTRIES: "GRASIM",
  PIDILITIND: "PIDILITIND", PIDILITE: "PIDILITIND", PIDILITEINDUSTRIES: "PIDILITIND",
  CIPLA: "CIPLA",
  DIVISLAB: "DIVISLAB", DIVISLABORATORIES: "DIVISLAB",
  TECHM: "TECHM", TECHMAHINDRA: "TECHM",
  HINDUNILVR: "HINDUNILVR", HINDUSTAN: "HINDUNILVR", HINDUSTANUNILEVER: "HINDUNILVR", HUL: "HINDUNILVR",
  TATAMOTORS: "TATAMOTORS",
  ADANI: "ADANIENT", ADANIENT: "ADANIENT", ADANIENTERPRISE: "ADANIENT", ADANIENTERPRISES: "ADANIENT",
  ADANIPORTS: "ADANIPORTS", ADANIPORT: "ADANIPORTS",
  PERSISTENT: "PERSISTENT", PERSISTENTSYSTEMS: "PERSISTENT",
  LTIM: "LTIM", LTIMINDTREE: "LTIM", MINDTREE: "LTIM",
  MPHASIS: "MPHASIS",
  COFORGE: "COFORGE",
};

/** Global name-to-ticker map for common full names and crypto */
const GLOBAL_NAME_ALIASES: Record<string, string> = {
  // US / Global equities
  APPLE: "AAPL", MICROSOFT: "MSFT", GOOGLE: "GOOGL", ALPHABET: "GOOGL",
  AMAZON: "AMZN", META: "META", FACEBOOK: "META",
  TESLA: "TSLA", NVIDIA: "NVDA", NETFLIX: "NFLX",
  AMD: "AMD", ADVANCEDMICRODEVICES: "AMD",
  INTEL: "INTC", IBM: "IBM",
  JPMORGAN: "JPM", JPMORGANCHASE: "JPM",
  GOLDMANSACHS: "GS", GOLDMAN: "GS",
  BERKSHIRE: "BRK-B", BERKSHIREHATHAWAY: "BRK-B",
  COCACOLA: "KO", COKE: "KO",
  PEPSI: "PEP", PEPSICO: "PEP",
  DISNEY: "DIS", WALTDISNEY: "DIS",
  VISA: "V", MASTERCARD: "MA",
  WALMART: "WMT", COSTCO: "COST",
  BOEING: "BA", LOCKHEEDMARTIN: "LMT", LOCKHEED: "LMT",
  PALANTIR: "PLTR", SNOWFLAKE: "SNOW",
  UBER: "UBER", AIRBNB: "ABNB",
  SPOTIFY: "SPOT", SHOPIFY: "SHOP",
  PAYPAL: "PYPL", BLOCK: "SQ", SQUARE: "SQ",
  SALESFORCE: "CRM", ORACLE: "ORCL",
  QUALCOMM: "QCOM", BROADCOM: "AVGO",
  MICRON: "MU", COINBASE: "COIN",
  FORD: "F", GENERALMOTORS: "GM",
  PFIZER: "PFE", MODERNA: "MRNA",
  JOHNSON: "JNJ", JOHNSONANDJOHNSON: "JNJ",
  PROCTER: "PG", PROCTERANDGAMBLE: "PG", PROCTERANGAMBLE: "PG",
  EXXON: "XOM", EXXONMOBIL: "XOM",
  CHEVRON: "CVX",
  UNITEDHEALTH: "UNH", UNITEDHEALTHGROUP: "UNH",
  HOMEDEPOT: "HD",
  MCDONALDS: "MCD",
  STARBUCKS: "SBUX",
  NIKE: "NKE",
  SONY: "SONY",
  SAMSUNG: "005930.KS",
  ALIBABA: "BABA",
  // Crypto
  BITCOIN: "BTC-USD", BTC: "BTC-USD",
  ETHEREUM: "ETH-USD", ETH: "ETH-USD", ETHER: "ETH-USD",
  SOLANA: "SOL-USD", SOL: "SOL-USD",
  RIPPLE: "XRP-USD", XRP: "XRP-USD",
  DOGECOIN: "DOGE-USD", DOGE: "DOGE-USD",
  CARDANO: "ADA-USD", ADA: "ADA-USD",
  POLKADOT: "DOT-USD", DOT: "DOT-USD",
  AVALANCHE: "AVAX-USD", AVAX: "AVAX-USD",
  CHAINLINK: "LINK-USD", LINK: "LINK-USD",
  LITECOIN: "LTC-USD", LTC: "LTC-USD",
  POLYGON: "MATIC-USD", MATIC: "MATIC-USD",
  SHIBA: "SHIB-USD", SHIBAINU: "SHIB-USD",
  // Commodities
  GOLD: "GC=F", SILVER: "SI=F",
  CRUDEOIL: "CL=F", OIL: "CL=F", WTI: "CL=F", BRENT: "BZ=F",
  NATURALGAS: "NG=F",
  // Indices
  NIFTY: "^NSEI", NIFTY50: "^NSEI",
  SENSEX: "^BSESN",
  SP500: "^GSPC", SNP500: "^GSPC",
  NASDAQ: "^IXIC",
  DOWJONES: "^DJI", DOW: "^DJI",
};

function dedupe(values: string[]): string[] {
  return [...new Set(values.filter(Boolean))];
}

function normalizeIndianBase(rawBase: string): string {
  const compact = rawBase.replace(/[^A-Z0-9]/g, "");
  return INDIAN_ALIASES[compact] || compact;
}

export function normalizeTickerInput(rawTicker: string): string {
  let ticker = (rawTicker || "").trim().toUpperCase();
  if (!ticker) return "";

  // Strip common noise words
  ticker = ticker
    .replace(/\b(LIMITED|LTD|INC|CORP|CORPORATION|COMPANY|CO|GROUP|INDUSTRIES|ENTERPRISE|ENTERPRISES)\b/g, "")
    .trim();

  ticker = ticker
    .replace(/\.NSE$/, ".NS")
    .replace(/\.BSE$/, ".BO")
    .replace(/^NSE\s*:\s*/i, "")
    .replace(/^BSE\s*:\s*/i, "")
    .replace(/\s+/g, " ");

  // Check global name aliases first (handles "Bitcoin", "Apple", "Gold", etc.)
  const compactForGlobal = ticker.replace(/[^A-Z0-9]/g, "");
  const globalMatch = GLOBAL_NAME_ALIASES[compactForGlobal];
  if (globalMatch) return globalMatch;

  const exchange = /\.NS$/.test(ticker) ? "NS" : /\.BO$/.test(ticker) ? "BO" : null;
  const rawBase = ticker.replace(/\.(NS|BO)$/, "");
  const normalizedBase = normalizeIndianBase(rawBase);
  const looksIndian = Boolean(exchange) || KNOWN_INDIAN_BASE.has(normalizedBase);

  // Also check if the compact form matches an Indian alias
  const indianAliasMatch = INDIAN_ALIASES[compactForGlobal];
  if (indianAliasMatch && !globalMatch) {
    return `${indianAliasMatch}.${exchange || "NS"}`;
  }

  if (looksIndian) {
    return `${normalizedBase}.${exchange || "NS"}`;
  }

  // Keep global symbols untouched, except collapse accidental spaces for plain tickers
  if (!/[=\-^:.]/.test(ticker) && ticker.includes(" ")) {
    return ticker.replace(/\s+/g, "");
  }

  return ticker;
}

export function isIndianTicker(ticker: string): boolean {
  const normalized = normalizeTickerInput(ticker);
  if (!normalized) return false;
  if (normalized.endsWith(".NS") || normalized.endsWith(".BO")) return true;
  const compact = normalized.replace(/[^A-Z0-9]/g, "");
  return KNOWN_INDIAN_BASE.has(compact);
}

export function buildTickerCandidates(rawTicker: string): string[] {
  const normalized = normalizeTickerInput(rawTicker);
  if (!normalized) return [];

  const isIndian = isIndianTicker(normalized);
  const hasExchange = /\.(NS|BO)$/.test(normalized);
  const base = normalized.replace(/\.(NS|BO)$/, "");

  if (!isIndian) {
    return [normalized];
  }

  if (normalized.endsWith(".NS")) {
    return dedupe([normalized, `${base}.BO`, base]);
  }

  if (normalized.endsWith(".BO")) {
    return dedupe([normalized, `${base}.NS`, base]);
  }

  if (hasExchange) {
    return dedupe([normalized, base]);
  }

  return dedupe([`${base}.NS`, `${base}.BO`, base]);
}
