import { useNavigate } from "react-router-dom";
import { useEffect } from "react";
import PublicNav from "@/components/PublicNav";
import { FOOTER_DISCLAIMER } from "@/lib/sebiCompliance";

export default function DisclaimerPage() {
  const navigate = useNavigate();

  useEffect(() => {
    document.title = "Disclaimer | EntropyLite - Market Intelligence Platform";
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.setAttribute("content", "Legal disclaimer for EntropyLite market intelligence platform. EntropyLite provides probabilistic scenario analysis, not investment advice.");
  }, []);

  return (
    <div className="min-h-screen bg-white text-black">
      <PublicNav />

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-12 sm:py-20">
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-8">
          Disclaimer & Legal Notice
        </h1>

        <div className="space-y-8 text-sm sm:text-base text-black/60 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-black mb-3">No Investment Advice</h2>
            <p>
              EntropyLite is a market intelligence and probabilistic scenario engine. The platform provides 
              research-based observations, quantitative analysis, and scenario projections derived from publicly 
              available market data, statistical models, and AI-powered analytical engines.
            </p>
            <p className="mt-3">
              <strong className="text-black">EntropyLite does NOT provide investment advice, trading recommendations, 
              portfolio management services, or any form of financial advisory.</strong> All outputs, including 
              scenario assessments, confidence scores, projected ranges, risk metrics, and intelligence summaries,
              are informational in nature and should be treated as research tools, not instructions to buy, sell, 
              or hold any financial instrument.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-3">Probabilistic Outputs</h2>
            <p>
              All projections, scenario analyses, and confidence scores generated by EntropyLite are probabilistic 
              in nature. They represent statistical possibilities based on historical data, current market conditions, 
              and quantitative models, not certainties. Markets are inherently unpredictable, and no model or 
              system can guarantee accuracy of any forecast.
            </p>
            <p className="mt-3">
              Monte Carlo simulations, risk metrics (VaR, CVaR), and other quantitative outputs are based on 
              mathematical models with inherent assumptions and limitations. Past performance of any model, 
              scenario, or analytical output does not guarantee or indicate future results.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-3">Independent Decision-Making</h2>
            <p>
              Users of EntropyLite are solely responsible for their own investment decisions. The platform is 
              designed to enhance market understanding through data-driven intelligence, not to replace 
              independent judgment, due diligence, or professional financial advice.
            </p>
            <p className="mt-3">
              Before making any investment decision, users should consult with qualified financial advisors, 
              consider their individual financial situation, risk tolerance, and investment objectives, and 
              conduct their own independent research.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-3">Limitation of Liability</h2>
            <p>
              EntropyLite, its creators, affiliates, and contributors shall not be liable for any financial 
              losses, damages, or consequences arising from the use of or reliance on information, analyses, 
              or outputs provided by the platform. This includes, but is not limited to, direct, indirect, 
              incidental, consequential, or punitive damages.
            </p>
            <p className="mt-3">
              The platform is provided "as is" without warranties of any kind, express or implied, including 
              but not limited to warranties of accuracy, completeness, timeliness, merchantability, or fitness 
              for a particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-3">Data Sources & Accuracy</h2>
            <p>
              Market data, news, and other information used by EntropyLite are sourced from third-party 
              providers and publicly available sources. While the platform endeavors to use reliable data 
              sources, EntropyLite does not guarantee the accuracy, completeness, or timeliness of any 
              data or analytical output.
            </p>
            <p className="mt-3">
              Prediction market data, sentiment indicators, and consensus signals referenced within the 
              platform reflect third-party market opinions and are presented for informational context only.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-3">Regulatory Compliance</h2>
            <p>
              EntropyLite is not registered with, nor regulated by, the Securities and Exchange Board of 
              India (SEBI) or any other financial regulatory authority as an investment advisor, research 
              analyst, or portfolio manager. The platform operates as a technology product providing 
              market intelligence tools.
            </p>
            <p className="mt-3">
              Users are responsible for ensuring their use of the platform complies with applicable laws 
              and regulations in their jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-3">Contact</h2>
            <p>
              For questions regarding this disclaimer or the platform's capabilities, reach out via the 
              channels listed on our website.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-black/5 py-8">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="font-mono text-[10px] text-black/30">© {new Date().getFullYear()} EntropyLite. All rights reserved.</p>
          <div className="flex items-center gap-6">
            <button onClick={() => navigate("/")} className="font-mono text-[10px] text-black/30 hover:text-black/60">Home</button>
            <button onClick={() => navigate("/pricing")} className="font-mono text-[10px] text-black/30 hover:text-black/60">Pricing</button>
            <button onClick={() => navigate("/about")} className="font-mono text-[10px] text-black/30 hover:text-black/60">About</button>
          </div>
        </div>
      </footer>
    </div>
  );
}
