import { useEffect } from "react";
import PublicNav from "@/components/PublicNav";
import SiteFooter from "@/components/marketing/SiteFooter";
import { PageHeader } from "@/components/marketing/Section";

const SECTIONS: { n: string; title: string; body: string[] }[] = [
  {
    n: "01",
    title: "No investment advice",
    body: [
      "Entropy is a market-intelligence and probabilistic scenario engine. The platform provides research-based observations, quantitative analysis, and scenario projections derived from publicly available market data, statistical models, and AI-powered analytical engines.",
      "Entropy does NOT provide investment advice, trading recommendations, portfolio management services, or any form of financial advisory. All outputs — including scenario assessments, confidence scores, projected ranges, risk metrics, and intelligence summaries — are informational in nature and should be treated as research tools, not instructions to buy, sell, or hold any financial instrument.",
    ],
  },
  {
    n: "02",
    title: "Probabilistic outputs",
    body: [
      "All projections, scenario analyses, and confidence scores generated by Entropy are probabilistic in nature. They represent statistical possibilities based on historical data, current market conditions, and quantitative models — not certainties. Markets are inherently unpredictable, and no model or system can guarantee the accuracy of any forecast.",
      "Monte Carlo simulations, risk metrics (VaR, CVaR), and other quantitative outputs are based on mathematical models with inherent assumptions and limitations. Past performance of any model, scenario, or analytical output does not guarantee or indicate future results.",
    ],
  },
  {
    n: "03",
    title: "Independent decision-making",
    body: [
      "Users of Entropy are solely responsible for their own investment decisions. The platform is designed to enhance market understanding through data-driven intelligence, not to replace independent judgment, due diligence, or professional financial advice.",
      "Before making any investment decision, users should consult qualified financial advisors, consider their individual financial situation, risk tolerance, and investment objectives, and conduct their own independent research.",
    ],
  },
  {
    n: "04",
    title: "Limitation of liability",
    body: [
      "Entropy, its creators, affiliates, and contributors shall not be liable for any financial losses, damages, or consequences arising from the use of, or reliance on, information, analyses, or outputs provided by the platform. This includes, but is not limited to, direct, indirect, incidental, consequential, or punitive damages.",
      'The platform is provided "as is" without warranties of any kind, express or implied, including but not limited to warranties of accuracy, completeness, timeliness, merchantability, or fitness for a particular purpose.',
    ],
  },
  {
    n: "05",
    title: "Data sources & accuracy",
    body: [
      "Market data, news, and other information used by Entropy are sourced from third-party providers and publicly available sources. While the platform endeavors to use reliable data sources, Entropy does not guarantee the accuracy, completeness, or timeliness of any data or analytical output.",
      "Prediction-market data, sentiment indicators, and consensus signals referenced within the platform reflect third-party market opinions and are presented for informational context only.",
    ],
  },
  {
    n: "06",
    title: "Regulatory position",
    body: [
      "Entropy is not registered with, nor regulated by, the Securities and Exchange Board of India (SEBI) or any other financial regulatory authority as an investment advisor, research analyst, or portfolio manager. The platform operates as a technology product providing market-intelligence tooling.",
      "Users are responsible for ensuring their use of the platform complies with applicable laws and regulations in their jurisdiction.",
    ],
  },
  {
    n: "07",
    title: "Contact",
    body: [
      "For questions regarding this disclaimer or the platform's capabilities, reach out via the channels listed on our website.",
    ],
  },
];

export default function DisclaimerPage() {
  useEffect(() => {
    document.title = "Disclaimer | Entropy";
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.setAttribute("content", "Legal disclaimer for the Entropy market-intelligence platform. Entropy provides probabilistic scenario analysis, not investment advice.");
  }, []);

  return (
    <div className="site-public min-h-screen bg-carbon-950 text-white">
      <PublicNav />

      <PageHeader
        label="Legal"
        title={<>Disclaimer &amp; legal notice.</>}
        lede="Read this before relying on any output of the platform. Entropy is a research instrument — every decision remains yours."
      />

      <main className="max-w-7xl mx-auto px-5 sm:px-8 py-16 sm:py-24">
        <div className="lg:max-w-2xl">
          {SECTIONS.map((s) => (
            <section key={s.n} className="border-t border-hairline py-10 first:border-t-0 first:pt-0">
              <div className="flex items-center gap-3 mb-4">
                <span className="mkt-label text-[10px] text-white/30">{s.n}</span>
                <h2 className="text-[17px] font-semibold tracking-tight text-white">{s.title}</h2>
              </div>
              {s.body.map((p, i) => (
                <p key={i} className="text-[14.5px] text-white/55 leading-relaxed mb-4 last:mb-0">
                  {p}
                </p>
              ))}
            </section>
          ))}
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
