-- Delete the stored Platt calibration row.
--
-- The nightly calibration-fit stored α=0.9672, β=0, γ=−2.6675. At full
-- consensus (ensemble score 1, agreement 1) that curve tops out at
-- σ(α+β+γ) = 15%, which the consumer clamps to the 0.50 floor — so every
-- ticket read exactly 50% calibrated probability, no gate could ever pass,
-- and Direct Profit could not produce a single BUY/SELL.
--
-- The stored fit is no longer consumed anywhere (the engine runs on the
-- priors; calibration-fit keeps fitting for observability only and deletes
-- this row on every run). Deleting it also heals older deployed engine
-- builds, whose loader falls back to the priors when the row is absent.
delete from public.calibration_params where id = 1;
